### ISSUE TITLE
As an user I want to have opportunity to use Sonar-operator without EDP

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-sonar-operator#3]
Acceptance Criteria:

- user can deploy sonar-operator without EDP;
- sonar-operator can configure Sonar LTS version with main sonar-operator capabilities (User provisioning, QG, QP);
- publish sonar-operator to operator hub;
- align EDP install to use new sonar-operator approach;

**Comment by SergK** [comment]
Implemented
